# Generated by Django 4.1.7 on 2023-04-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0002_order_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
